version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: itinerary_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: itineraryDB

  api:
    build: .
    container_name: itinerary_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/itineraryDB
    restart: always

volumes:
  mongo_data:
